SASFW/Controllers/BlogController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLayer;
using Microsoft.AspNetCore.Mvc;
using PresentationLayer;

namespace SASFW.Controllers
{
    public class BlogController : Controller
    {
        private DataManager _dataManager;
        private ServicesManager _servicesManager;

        public BlogController(DataManager dataManager)
        {
            _dataManager = dataManager;
            _servicesManager = new ServicesManager(dataManager);
        }

        public IActionResult Index()
        {
            ///TODO:3005 - hard code (replace on types dependency)
            var _blogDirectory = _servicesManager.Directorys.GetDirectoryViewModelByDirectoryId(15);
            return View(_blogDirectory);
        }

        public IActionResult BlogItem(int itemId)
        {
            var _blogItem = _servicesManager.Directorys.GetMaterialPageViewModelByMaterialId(itemId);
            return View(_blogItem);
        }
    }
}

SASFW/Controllers/PortfolioController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using BusinessLayer;
using Microsoft.AspNetCore.Mvc;
using PresentationLayer;

namespace SASFW.Controllers
{
    public class PortfolioController : Controller
    {
        private DataManager _dataManager;
        private ServicesManager _servicesManager;

        public PortfolioController(DataManager dataManager)
        {
            _dataManager = dataManager;
            _servicesManager = new ServicesManager(dataManager);
        }

        public IActionResult Index()
        {
            ///TODO:3005 - hard code (replace on types dependency)
            var _portfolioDirectory = _servicesManager.Directorys.GetDirectoryViewModelByDirectoryId(1);
            return View(_portfolioDirectory);
        }

        public IActionResult PortfolioItem(int itemId)
        {
            var _portfolioItem = _servicesManager.Directorys.GetMaterialPageViewModelByMaterialId(itemId);
            return View(_portfolioItem);
        }
    }
}

SASFW/Views/Shared/WhiteLayout.cshtml
<!DOCTYPE html>
<html class="is-menu-fixed js flexbox canvas canvastext webgl no-touch geolocation postmessage websqldatabase indexeddb hashchange history draganddrop websockets rgba hsla multiplebgs backgroundsize borderimage borderradius boxshadow textshadow opacity cssanimations csscolumns cssgradients cssreflections csstransforms csstransforms3d csstransitions fontface generatedcontent video audio localstorage sessionstorage webworkers applicationcache svg inlinesvg smil svgclippaths csstransformspreserve3d mdl-js" style="">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="Web-developer blog">
    <meta name="keywords" content="developer, blog, asp.core, c#">
    <meta name="author" content="Aleksander Sazhin">
    <link rel="icon" type="image/png" href="/images/favicon96.png" />

    <title>@(string.IsNullOrEmpty((string)ViewData["Title"]) ? "Aleksander Sazhin's personal blog" : (string)ViewData["Title"])</title>

    <!-- FONTS -->
    <!-- STYLES -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="~/css/new/bootstrap.min.css">

    <link rel="stylesheet" type="text/css" href="~/css/new/fontello.css">
    <link rel="stylesheet" type="text/css" href="~/css/new/uniform.default.css">
    <link rel="stylesheet" type="text/css" href="~/css/new/magnific-popup.css">
    <link rel="stylesheet" type="text/css" href="~/css/new/fluidbox.css">
    <link rel="stylesheet" type="text/css" href="~/css/new/owl.carousel.css">
    <link rel="stylesheet" type="text/css" href="~/css/new/selection-sharer.css">
    <link rel="stylesheet" type="text/css" href="~/css/new/elastislide.css">
    <link rel="stylesheet" type="text/css" href="~/css/new/align.css">
    <link rel="stylesheet" type="text/css" href="~/css/new/main.css">
    <link rel="stylesheet" type="text/css" href="~/css/new/768.css">
    <link rel="stylesheet" type="text/css" href="~/css/new/992.css">

    <!-- INITIAL SCRIPTS -->
    <script src="~/js/new/jquery-1.11.1.min.js"></script>
    <script src="~/js/new/jquery-migrate-1.2.1.min.js"></script>
    <script src="~/js/new/modernizr.min.js"></script>
    <!--[if lt IE 9]>
        <script src="js/ie.js"></script>
    <![endif]-->
    <!-- InstanceBeginEditable name="head" -->
    <!-- InstanceEndEditable -->


    <style id="fit-vids-style">
        .fluid-width-video-wrapper {
            width: 100%;
            position: relative;
            padding: 0;
        }

            .fluid-width-video-wrapper iframe, .fluid-width-video-wrapper object, .fluid-width-video-wrapper embed {
                position: absolute;
                top: 0;
                left: 0;
                width: 100%;
                height: 100%;
            }
        .progress{
            overflow:visible;
        }
    </style>

    <link type="text/css" rel="stylesheet" href="chrome-extension://pioclpoplcdbaefihamjohnefbikjilc/content.css">
</head>
<body>
    <!-- page -->
    <div id="page" class="hfeed site">

        <!-- header -->
        <header id="masthead" class="site-header" role="banner">

            <!-- site-navigation -->
            <nav id="primary-navigation" class="site-navigation primary-navigation" role="navigation">

                <a class="menu-toggle"><span class="lines"></span></a>

                <!-- nav-menu -->
                <div class="nav-menu">
                    <ul>
                        <li>
                            <a href="/">Home</a>
                        </li>
                        <li><a asp-action="Index" asp-controller="Portfolio">Portfolio</a></li>
                        @*<li><a asp-action="Index" asp-controller="Blog">Blog</a></li>*@
                        <li>
                            <a asp-action="About" asp-controller="Home">About me</a>
                            <!-- level 2 -->
                        </li>
                        <li><a asp-action="Contact" asp-controller="Home">Contact</a></li>
                    </ul>
                </div>
                <!-- nav-menu -->
                @*<a class="search-toggle toggle-link"></a>*@

                <!-- search-container -->
                @*<div class="search-container">

                        <div class="search-box">
                            <form role="search" method="get" class="search-form" action="">
                                <label>
                                    Search for
                                    <input type="search" id="search-field" placeholder="type and hit enter" name="s">
                                </label>
                                <input type="submit" class="search-submit" value="Search">
                            </form>
                        </div>

                    </div>*@
                <!-- search-container -->
                <!-- social-container -->
                <div class="social-container">

                    <ul class="social">
                        <li><a class="facebook" target="_blank" href="https://www.facebook.com/profile.php?id=100006656046064"></a></li>
                        <li><a class="vkontakte" target="_blank" href="https://vk.me/brainotekalight"></a></li>
                        <li><a class="github" target="_blank" href="https://github.com/k2moz"></a></li>
                        @*<li><a class="telegram" target="_blank" href="https://t.me/k2moz"></a></li>*@

                    </ul>


                </div>
                <!-- social-container -->

            </nav>
            <!-- site-navigation -->
            <!-- site-title -->
            <h1 class="site-title">
                <a href="/" rel="home">
                    <img src="/images/Lologo.png" alt="logo">
                    <!--EDITOR-->
                </a>
            </h1>
            <!-- site-title -->
            <!--<h1 class="site-title">
                <a href="../index.html" rel="home">
                    EDITOR
                </a>
            </h1>
            <p class="site-description">just another minimalist theme.</p>-->

        </header>
        <!-- header -->
        <!-- site-main -->
        <div id="main" class="site-main">




            <!-- primary -->
            <div id="primary" class="content-area">

                <!-- site-content -->
                <div id="content" class="site-content" role="main">
                    <!-- InstanceBeginEditable name="FeaturedContent" -->
                    <!-- InstanceEndEditable -->
                    <!-- layout-medium -->
                    <div class="layout-medium">
                        @RenderBody()
                    </div>
                </div>
                <!-- site-content -->

            </div>
            <!-- primary -->




        </div>
        <!-- site-main -->
        <!-- site-footer -->
        <footer id="colophon" class="site-footer" role="contentinfo">

            <!-- layout-medium -->
            <div class="layout-medium">

                <!-- footer-social -->
                <div class="footer-social">

                    <ul class="social">

                        @*<li><a class="telegram" target="_blank" href="https://t.me/k2moz"></a></li>*@
                        <li>
                            <a class="facebook" target="_blank" href="https://www.facebook.com/profile.php?id=100006656046064"></a>
                        </li>
                        <li><a class="vkontakte" target="_blank" href="https://vk.me/brainotekalight"></a></li>
                        <li><a class="github" target="_blank" href="https://github.com/k2moz"></a></li>
                    </ul>

                </div>
                <!-- footer-social -->
                <!-- footer-sidebar -->
                <div class="footer-sidebar widget-area" role="complementary">

                    <!-- widget -->
                    <aside class="widget widget_text">
                        <h3 class="widget-title">About me</h3>
                        <div class="textwidget">
                            <img src="/images/about-small.jpg" alt="avatar"> <p>I'm a professional web developer from Moscow. I work with projects of customers, companies and my projects.</p>
                        </div>
                    </aside>
                    <!-- widget -->
                    <!-- widget -->
                    @*<aside class="widget widget_tag_cloud">
                            <h3 class="widget-title">Тэги</h3>
                            <div class="tagcloud"> <a href="http://themes.pixelwars.org/editor-html/home-alt.html#" title="1 topic" style="font-size: 8pt;">adaptive</a> <a href="http://themes.pixelwars.org/editor-html/home-alt.html#" title="2 topics" style="font-size: 22pt;">design</a> <a href="http://themes.pixelwars.org/editor-html/home-alt.html#" title="1 topic" style="font-size: 8pt;">html</a> <a href="http://themes.pixelwars.org/editor-html/home-alt.html#" title="2 topics" style="font-size: 22pt;">responsive</a> <a href="http://themes.pixelwars.org/editor-html/home-alt.html#" title="2 topics" style="font-size: 22pt;">think</a> <a href="http://themes.pixelwars.org/editor-html/home-alt.html#" title="1 topic" style="font-size: 8pt;">web design</a> <a href="http://themes.pixelwars.org/editor-html/home-alt.html#" title="1 topic" style="font-size: 8pt;">css</a> <a href="http://themes.pixelwars.org/editor-html/home-alt.html#" title="2 topics" style="font-size: 22pt;">animations</a> <a href="http://themes.pixelwars.org/editor-html/home-alt.html#" title="1 topic" style="font-size: 8pt;">layout</a> <a href="http://themes.pixelwars.org/editor-html/home-alt.html#" title="2 topics" style="font-size: 14pt;">mobile</a> <a href="http://themes.pixelwars.org/editor-html/home-alt.html#" title="2 topics" style="font-size: 22pt;">think</a> <a href="http://themes.pixelwars.org/editor-html/home-alt.html#" title="1 topic" style="font-size: 8pt;">typography</a> </div>
                        </aside>*@
                    <!-- widget -->
                    <!-- widget : categories -->
                    @*<aside class="widget widget_categories">
                            <h3 class="widget-title">Категории</h3>
                            <ul>
                                <li class="cat-item"><a href="#" title="View all posts filed under Nature">Nature</a></li>
                                <li class="cat-item"><a href="#" title="View all posts filed under Life">Life</a></li>
                                <li class="cat-item"><a href="#" title="View all posts filed under Adventure">Adventure</a></li>
                                <li class="cat-item"><a href="#" title="View all posts filed under Freebies">Travel</a></li>
                                <li class="cat-item"><a href="#" title="View all posts filed under Sport">Sport</a></li>
                            </ul>
                        </aside>*@
                    <!-- widget : categories -->
                    <!-- widget -->
                    @*<aside class="widget widget_recent_entries">
                            <h3 class="widget-title">Последние записи</h3>
                            <ul>
                                <li><a href="#">Runaway A Road Adventure</a></li>
                                <li><a href="#">All In Our Head</a></li>
                                <li><a href="#">Smaller Plate</a></li>
                                <li><a href="#">Alice On The Roof</a></li>
                                <li><a href="#">Becoming A DragonFly</a></li>
                            </ul>
                        </aside>*@
                    <!-- widget -->


                </div>
                <!-- footer-sidebar -->


            </div>
            <!-- layout-medium -->
            <!-- .site-info -->
            @*<div class="site-info">

                    <!-- layout-medium -->
                    <div class="layout-medium">

                        <p>crafted with <i class="pw-icon-heart"></i> <em>by</em></p>

                    </div>
                    <!-- layout-medium -->

                </div>*@
            <!-- .site-info -->



        </footer>
        <!-- site-footer -->

    </div>
    <!-- page -->


    <script src="~/js/new/fastclick.js"></script>
    <script src="~/js/new/jquery.fitvids.js"></script>
    <script src="~/js/new/jquery.validate.min.js"></script>
    <script src="~/js/new/jquery.uniform.min.js"></script>
    <script src="~/js/new/imagesloaded.pkgd.min.js"></script>
    <script src="~/js/new/jquery.isotope.min.js"></script>
    <script src="~/js/new/jquery.magnific-popup.min.js"></script>
    <script src="~/js/new/jquery.fluidbox.min.js"></script>
    <script src="~/js/new/owl.carousel.min.js"></script>
    <script src="~/js/new/readingTime.js"></script>
    <script src="~/js/new/selection-sharer.js"></script>
    <script src="~/js/new/r-gallery.js"></script>


    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>


    <link href="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.css" rel="stylesheet">
    <script src="http://cdnjs.cloudflare.com/ajax/libs/summernote/0.8.9/summernote.js"></script>

    <script src="~/js/new/main.js"></script>


    <!-- InstanceEnd -->
</body>
</html>

SASFW/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SASFW</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">SASFW</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2018 - SASFW</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-2.2.0.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-K+ctZQ+LL8q6tP7I94W+qzQsfRV2a+AfHIi9k8z8l9ggpc8X+Ytst4yBo/hH+8Fk">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>